apiRules:
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGLES1
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGLES3
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL\.Compatibility
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.Vulkan
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.Glx
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.Wgl
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.Egl
